vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        pictures:
            uri_prefix: /uploads/pictures
            upload_destination: '%kernel.project_dir%/public/uploads/pictures'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            delete_on_update: true
            delete_on_remove: true
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
